# I/O Settings
UDP_IP = '127.0.0.1'
UDP_ACCEL_PORT = 12345
UDP_TS_PORT = 12346

OUTPUT_IP = '127.0.0.1'
OUTPUT_PORT = 5557

# Run Settings
AXIS_VALUE_ROUNDING = 3
PRINT_RAW_AXIS_VALUES = False
PRINT_CLUSTER_VALUES = False
OUTPUT_DATA = True
PRINT_OUT = True

# Calculation Variables
NUM_CALIBRATION_POINTS = 150
NUM_POINTS_PER_ROLLING_AVG = 5
X_DELTA = 0.3  # roll
Z_DELTA = 0.3  # tilt
DOM_DELTA_MULT = 3
SUB_DELTA_MULT = 2

# String Constants
MOVE_FORWARD_MSG = 'LETS FLY!!'
MOVE_BACKWARD_MSG = 'DIVE!!!'
MOVE_RIGHT_MSG = 'RIGHT 4 REALZ'
MOVE_LEFT_MSG = 'LEFT'
CONTINUE_MSG = 'CONTINUE'
