# I/O Settings
UDP_IP = '127.0.0.1'
UDP_PORT = 12345

# Run Settings
AXIS_VALUE_ROUNDING = 3
PRINT_RAW_AXIS_VALUES = False
PRINT_CLUSTER_VALUES = False

# Calculation Variables
NUM_CALIBRATION_POINTS = 30
NUM_POINTS_PER_ROLLING_AVG = 5
X_DELTA = 0.3
Z_DELTA = 0.3

# String Constants
MOVE_FORWARD_MSG = 'LETS FLY!!'
MOVE_BACKWARD_MSG = 'DIVE!!!'
MOVE_RIGHT_MSG = 'RIGHT 4 REALZ'
MOVE_LEFT_MSG = 'LEFT'
CONTINUE_MSG = 'CONTINUE'
